[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "stdiomask>=0.0.6",
]
